'use strict'

// Generates app/addons/addons.yml from whatever native-addon xcframeworks
// `bare-link` resolved into app/addons/. project.yml `include`s this file so
// Xcode embeds each framework in the app bundle.
//
// This removes the usual hand-transcription of addon names + versions: the
// linker already knows them, so we derive the list instead of typing it.

const fs = require('fs')
const path = require('path')

const ADDONS_DIR = path.join(__dirname, '..', 'app', 'addons')

// bare-link emits universal `.framework`s for the darwin preset (single
// platform) and `.xcframework`s for multi-slice presets like ios.
const frameworks = fs
  .readdirSync(ADDONS_DIR)
  .filter((name) => name.endsWith('.framework') || name.endsWith('.xcframework'))
  .sort()

const lines = [
  '# Generated by `npm run addons` from app/addons/*.xcframework — do not edit.',
  'targets:',
  '  BareSwitch:',
  '    dependencies:'
]

for (const framework of frameworks) {
  lines.push(`      - framework: ${framework}`)
}

fs.writeFileSync(path.join(ADDONS_DIR, 'addons.yml'), lines.join('\n') + '\n')

console.log(`Wrote ${frameworks.length} addon framework(s) to app/addons/addons.yml`)
